trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:  
- task: PowerShell@2
  displayName: Build
  inputs:
    targetType: 'inline'
    script: |
      docker build -t june05dockerimg .
    workingDirectory: '$(Build.SourcesDirectory)'
  
- task: PowerShell@2
  displayName: Tag
  inputs:
    targetType: 'inline'
    script: |
      docker tag june05dockerimg skaran225/june05dockerimg:latest
    workingDirectory: '$(Build.SourcesDirectory)'

- task: PowerShell@2
  displayName: Log-in                   	# for ACR password will be Access key
  inputs:
    targetType: 'inline'
    script: |
      docker login -u skaran225 -p Th@kur63225			
    workingDirectory: '$(Build.SourcesDirectory)'

- task: PowerShell@2
  displayName: Push
  inputs:
    targetType: 'inline'
    script: |
      docker push skaran225/june05dockerimg:latest
    workingDirectory: '$(Build.SourcesDirectory)'

- task: PowerShell@2
  displayName: 'Deploy to OpenShift'
  inputs:
    targetType: 'inline'
    script: |
      oc login --token=sha256~PeQALrY8853JjEoEvs2FBWIG_OvMN_eEHurymQx9EdY --server=https://api.sandbox-m4.g2pi.p1.openshiftapps.com:6443
      oc project skaran225-dev
      oc new-app skaran225/june05dockerimg --name=june05wom
      oc expose service june05wom
    workingDirectory: '$(Build.SourcesDirectory)'
